version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nutri-mind-backend
    command: uvicorn user_profile_api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGO_URL=mongodb://mongo:27017
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: nutri-mind-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nutri-mind-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  mongo_data: 